# ONNX Runtime Configuration for P.U.L.S.E. (Prime Uminda's Learning System Engine)
# Optimized for 4GB RAM constraints

# Runtime settings
onnx_runtime:
  # Thread settings (critical for memory usage)
  intra_op_num_threads: 1
  inter_op_num_threads: 1

  # Execution mode - sequential is more memory-efficient
  execution_mode: sequential

  # Optimization level (1 = basic optimizations)
  optimization_level: 1

  # Memory settings
  memory:
    # Hard cap for 4GB systems (in MB)
    max_working_set: 500
    # Memory allocation strategy
    arena_extend_strategy: kSameAsRequested
    # Enable memory pattern optimization
    enable_memory_pattern: true
    # Use memory arena for allocations
    enable_mem_arena: true

# DistilBERT model settings
distilbert:
  # Maximum sequence length (reduced from default 512)
  max_length: 128

  # Always truncate long inputs
  truncation: true

  # Process one sample at a time
  batch_size: 1

  # Use half-precision for reduced memory
  precision: fp16

  # Disable attention mask reuse
  reuse_attention_mask: false

# System constraints
system:
  # Memory threshold for fallback to regex (MB)
  memory_threshold: 300

  # Maximum model size for 4GB system (MB)
  max_model_size: 200

  # Force garbage collection after each inference
  force_gc: true
